@startuml

'left to right direction


together {
package Frontend:Reactjs {
}

package Grafana {
}
}

"Frontend:Reactjs" --> "Backend:Spring"

package Backend:Spring {
interface RtcService <<websocket>>

class MessagePersistentService {}

}


MessagePersistentService --> "postgres/citus (cluster)": persist message
MessagePersistentService --> "kafka": publishing


together {
package "postgres/citus (cluster)" {
    class Message {
        global_channel_id: paritioned
        timestamp: clustered, b-tree indexed
        content
        
    }
}

package kafka <<node>> {

}

}

"kafka" --> "clickhouse (cluster)"
"kafka" --> "elasticsearch (cluster)"



together {
    package "clickhouse (cluster)" <<node>> {
    }

    package "elasticsearch (cluster)" <<node>> {
    }
}

"Backend:Spring" --> "elasticsearch (cluster)": search APIs

Grafana --> "clickhouse (cluster)": monitoring

@enduml