
create table rtc_app.global_channel
(
    channel_id   integer generated by default as identity
        primary key,
    channel_name varchar(255) unique
);



-- create partitioned table
create table rtc_app.global_msg
(
    msg_id            integer not null generated by default as identity,
    account_name      varchar(255),
    message           TEXT,
    timestamp         timestamp(6),
    global_channel_id integer,
    constraint fk_channel_msg foreign key (global_channel_id) references global_channel(channel_id)

) partition by list(global_channel_id);
CREATE INDEX timestamp_btree_index ON rtc_app.global_msg(timestamp);
cluster rtc_app.global_msg USING timestamp_btree_index;

-- create partition script
create table rtc_app.global_msg_xxx partition of rtc_app.global_msg for values in (1);
alter table rtc_app.global_msg_xxx
    add primary key (msg_id);







